- infra/conf/command/command.go
fix https://github.com/v2ray/v2ray-core/issues/1666
os.Stdin in windows does not compatible with TeeReader. 
This bug is triggered only when config.json is relatively large, eg 10k. I looked around find that in early version of go there's such issue: https://github.com/golang/go/issues/13697 `// Windows can't read bytes over max of int16. `
In recent version this code moved to https://github.com/golang/go/blob/master/src/internal/poll/fd_windows.go
In v2ray, this reader is passed to https://github.com/v2fly/v2ray-core/blob/1a7b2337f81cbdbe7da06d5cf5c916de899ef372/common/buf/io.go#L49 and generated a `SingleReader`,  https://github.com/v2fly/v2ray-core/blob/1a7b2337f81cbdbe7da06d5cf5c916de899ef372/common/buf/reader.go#L157   which reads one buffer at a time, thus excceed the windows stdin …
> fix stdin type mismatch in windows

- infra/conf/dns_proxy.go
`go vet` complains the following errors:
```
$ cd $GOPATH/src/v2ray.com/core/infra/conf
$ go vet
./dns_proxy.go:10:2: struct field tag `json:network` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
./dns_proxy.go:11:2: struct field tag `json:address` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
./dns_proxy.go:12:2: struct field tag `json:port` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```
The `DnsOutboundConfig` fileld tags are missing double quotes.
> fix: json field tag syntax

- azure-pipelines.template.yml
- azure-pipelines.yml
前几天我就看了 Azure Pipelines 关于 Golang 的文档，发现尚不支持如“latest”这样的版本声明方式
或许以后可以自动化这个常规流程
> Update Golang version to 1.14.4

- proxy/http/client.go
- transport/internet/tls/tls.go
v2ray/v2ray-core#2488 ~~v2ray/v2ray-core#2521~~
> 使http outbound支持连接https与http/2代理服务器

- infra/conf/shadowsocks.go
There is a trend to use TLS nowadays. When proxy traffic is wrapped inside TLS, extra encryption typically bring no value. I found v2ray actually support Shadowsocks cipher "none" already. It's just not parsing Json correctly.
I tested this implementation is compatible with other third party clients. I also did a quick test against Socks with no authentication. It looks like Shadowsocks yield a lower RTT.
NOTE: when "none" cipher is used, "password" is not verified. User need to rely on a secure path at transport level like ws or h2.
> Fix parser for shadowsocks cipher "none"

- common/buf/buffer_test.go
- common/mux/server.go
- features/stats/stats.go
note: there are other typos in external/ folder.
considering the fact that the folder "will be removed in future", I skipped those typos.
details: https://goreportcard.com/report/github.com/v2fly/v2ray-core#misspell
> some typo fixes

- Dockerfile
This error was caused by replacing wget with curl in c7b5d178b7e6c09c846bdbc1f75674ecee3cee11.
```bash
>>> Downloading newest geoip ...
./release/user-package.sh: line 53: curl: command not found
```
https://github.com/v2fly/v2ray-core/blob/34d6818a85ae75040350fb34bfdd6752a2c62420/release/user-package.sh#L51-L57
> Fix the error of missing curl in Dockerfile

- .github/workflows/docker.yaml
Resolved #45. This action will be triggered when the `master` branch commits a `tag` beginning with `v`.
1. Need to configure `DOCKER_USERNAME` and `DOCKER_ PASSWORD` in `Secrets`. If this commit needs to be merged into upstream `v2ray` in the future, please also keep this in mind.
2. Now supports build Linux 386 / amd64 / armv7 / arm64.
3. The build time is about 12 minutes. Each schema will only be built once, because the `latest` tag will hit the cache.
[GitHub Actions](https://github.com/kallydev/v2ray-core/actions?query=workflow%3A%22Release+Docker+image%22)
[Docker Hub](https://hub.docker.com/r/kallydev/v2fly-core/tags)
> Add docker.yaml to actions

- transport/internet/sockopt_darwin.go
- transport/internet/sockopt_freebsd.go
- transport/internet/sockopt_linux.go
- transport/internet/sockopt_other.go
- transport/internet/sockopt_windows.go
- transport/internet/system_listener.go
Fix #69
Fix https://github.com/v2ray/v2ray-core/issues/1971
https://github.com/v2ray/v2ray-core/pull/2228 最初的意愿或许是将`SO_REUSEPORT`的设置放到一个合适的始终会被调用的地方。但`applyInboundSocketOptions`及相关函数的设计关注`Sockopt`应为非空，从而使得`Sockopt`未设置时，设置`SO_REUSEPORT`的代码并不会被执行。
这个PR将与`SocketConfig`无关的`SO_REUSEPORT`设置移至`applyInboundSocketOptions`外面，同时取消对`getControlFunc`的检查（检查的目的是为了不注册一个空的Control函数，但现在有一个必定要执行的`SO_REUSEPORT`了）。
> Move setting of SO_REUSEPORT out of applyInboundSocketOptions

- app/dns/dohdns.go
With this, DoH client can automatically enable http2 if server (very likely) supports it. It hopefully reduces latency, which is very crucial for DNS.
> Enable ForceAttemptHTTP2 on DoH client

- proxy/http/client.go
Sorry to open a new pull request, because I forgot to do some change in the old one (#73)
> Fix http outbound to get correct TLS negotiated protocol when "stats" setting exists

- app/proxyman/inbound/inbound.go
- common/session/context.go
- common/session/session.go
- proxy/dokodemo/dokodemo.go
Fix #75 
对于 #75 的解决方案是利用Context传递Sockopt至DokodemoDoor的构造过程。这个实现比较微妙，因为实际上调用`Dokodemo.Process(..)`的`tcpworker`与`udpworker`中，已经存了一份StreamSettings了：
https://github.com/v2fly/v2ray-core/blob/45bf57826d8006f2b2b4e2e44f047064cfa05293/app/proxyman/inbound/worker.go#L64-L100
但经过分析后，发现在不改动公开接口的前提下很难将worker的stream settings直接在Process函数中取得。最后改动较小且有效的方案是通过Context传递。但是根据Go官方的理念，Context似乎并不应该被用于传递”可选参数“，同时在Inbound的Process中修改Context的后续影响范围也十分大，因此不应选择在此传入Sockopt。
最后选择了作用域小（构造Inbound前设置Sockopt，Inbound的构造也不会继续将Context传至更深的地方），资源占用小（仅在一次构造中设置Context）的本PR解决方案。
另本打算添加测试Dokodemo TProxy Sockopt的测试代码，但由于Mocks模块里缺少dispatcher与policy manager等模块的mock功能，因而代码编写过于复杂……此外SO_MARK的相关测试也似乎被Skip掉了，故没有继续下去。
> Apply sockopt from inbound config to dokodemo tproxy's response connection

- app/dns/server.go
- app/dns/server_test.go
- app/dns/udpns.go
- infra/conf/router.go
Closes #88
Fixes https://github.com/v2ray/v2ray-core/issues/2618
Possibly fixes https://github.com/v2ray/v2ray-core/issues/1913
Possibly fixes https://github.com/v2ray/v2ray-core/issues/2615
新增测试中，`Mijia Cloud`被以`Mijia\ Cloud`格式送往测试DNS并查询成功，但在`/etc/hosts`中添加带空格的条目失败，未能验证实际环境中是否不会出问题。
> Dotless and local domain support in built-in DNS

- app/dns/hosts.go
- app/dns/server.go
- app/dns/server_test.go
- app/router/condition.go
- common/strmatcher/domain_matcher.go
- common/strmatcher/domain_matcher_test.go
- common/strmatcher/full_matcher.go
- common/strmatcher/full_matcher_test.go
- common/strmatcher/strmatcher.go
Closes #92 
采用了#92中的方案二：`MatcherGroup`返回所有匹配的记录，`DomainMatcher`保留所有插入的记录。
> Amend domain matcher with returning array of all matches

- app/dns/server_test.go
- common/strmatcher/domain_matcher.go
- common/strmatcher/domain_matcher_test.go
Fixes https://github.com/v2fly/v2ray-core/issues/92#issuecomment-673219805
> Amend domain matcher with returning values of all matched subdomains

- common/strmatcher/strmatcher_test.go
Fix https://github.com/v2fly/v2ray-core/issues/92#issuecomment-673238489
根据链接中@Loyalsoldier 提供的质量极好的测试用例，为StrMatcher中的MatcherGroup提供测试。
测试结果按https://github.com/v2fly/v2ray-core/issues/92#issuecomment-673271102 中的输出为准。
> Supply test for domain matcher group

- proxy/http/client.go
Previous http outbound has 1 extra round-trip time to set up a CONNECT method tunnel. The client sends a CONNECT method request, waits for `200 OK` response from server, then sends tunnelled payload.
This commit eliminates the extra RTT by sending first client payload (probably the ClientHello of tunnelled connection) immediately after the CONNECT method request, without waiting for `200 OK` from server. This mechanism has been implemented in NaiveProxy and proves to work.
BTW, the Proxy-Connection header only takes effect for http/1.x, so I deleted it for h2.
> Reduce extra RTT when setting up CONNECT tunnel in http outbound (not vmess through http)

- transport/internet/http/hub.go
Use X-Forwarded-For header (if present) to get remote address. The WS transport already had this feature 2 years ago. Now with a properly configured reverse proxy, we can log the real client IP when works in H2 or WS transport.
> Parse X-Forwarded-For in http transport

- app/dns/server.go
#148 Fixes the panic, but the root cause of the panic is: the `ipIndexMap` array is designed to be consistent with `clients` array in length. When `servers` is an empty array, a localhost nameserver is appended, but `ipIndexMap` isn't changed, thus the consistency is broken.
> Fix: Append nil to ipIndexMap when appending default local name server

- app/router/condition_geoip_test.go
- app/router/condition_test.go
- infra/conf/dns_test.go
They can now reside in system path (like /usr/share/v2ray), so it's not
possible to copy into there.
> Don't copy assets if they are already present

- app/dispatcher/default.go
- app/router/condition.go
- app/router/condition_test.go
- app/router/config.go
- app/router/router.go
- app/router/router_test.go
- common/session/session.go
- features/routing/context.go
- features/routing/router.go
- features/routing/session/context.go
~~This PR is suspended after version 4.28.0 gets released.~~
This PR implements the routing context mentioned in https://github.com/v2fly/v2ray-core/issues/105#issuecomment-678340292:
```go
type Context interface {
GetInboundTag() string
GetSourceIPs() []net.IP
GetSourcePort() net.Port
GetTargetIPs() []net.IP
GetTargetPort() net.Port
GetTargetDomain() string
GetNetwork() net.Network
GetProtocol() string
GetUser() *protocol.MemoryUser
GetAttributes() map[string]interface{}
}
```
After this PR, the `Router` feature uses this context interface instead of `context.Context`.
> Extract session information during routing as routing context

- app/stats/command/command.go
- app/stats/stats.go
- app/stats/stats_test.go
- features/stats/stats.go
Currently, `app/stats` supports `Counter` mechanism for statistics like uplink/downlink. 
This PR implements a new `Channel` mechanism, enabling one app to register a channel and send data to it, while other apps could subscribe to this channel and receive messages, which is, an Observer pattern.
For #105, `statsManager` could register a channel, where `router` app get this channel and send routing context to this channel after one routing request,  and `stats` service could subscribe to this channel, receiving the routing context and send it to the client. 
The same mechanism could also be applied to built-in DNS service, and possibly built-in outbound health check in the future.
> Support Subscribing Channel in Statistics Manager

- app/stats/stats.go
- features/stats/stats.go
`Unregister` function should not return error when unregistering a counter/channel that's not in manager. This will cause double unregistering fails with error.
> Add UnregisterChannel & Modify unregistering logic

- app/router/condition.go
- app/router/condition_test.go
- common/session/session.go
- features/routing/context.go
- features/routing/session/context.go
Fixes https://github.com/v2fly/v2ray-core/issues/184
I suddenly decided to use email string instead of `*protocol.MemoryUser` for `Context.GetUser()` just before the merging of https://github.com/v2fly/v2ray-core/pull/108. This change didn't get well considered and reviewed and eventually caused the error in #184.
This PR adds nil check for `session.Inbound.User`. (I got really screwed by golang's NPE problem and nil check mechanism...) 
This modification was well reviewed, that no attribute is really saved in `interface{}`. They're all set as string and used as string, saving them as string directly can help a lot of things, like the serialization of gRPC API's routing stats.
> Routing Context: Fix GetUser() & Use string for Attributes Value

- transport/internet/kcp/config.go
It's very annoying to see many meaningless `NewAEADAESGCMBasedOnSeed` lines, once per connection, in v2ray core logs. This PR/commit will remove this.
-----
<table><tr><th>Before</th><th>After</th></tr><tr><td>
<td><img src="https://user-images.githubusercontent.com/7822648/93708585-17a4c180-fb6a-11ea-9b7c-e3e0b3c07de9.png"></td>
</tr></table>
> kcp: removing annoying NewAEADAESGCMBasedOnSeed hint

- app/dispatcher/default.go
- app/router/router.go
- app/router/router_test.go
- features/routing/dns/context.go
- features/routing/dns/errors.generated.go
- features/routing/router.go
For now, routing result (return value of `Router.PickRoute`) is the tag of the outbound. To provide richer information to the client, this PR implements a new interface `Route` as the result of `Router.PickRoute`.
```go
// PickRoute returns a route decision based on the given routing context.
PickRoute(ctx Context) (Route, error)
```
A `Route` is a routing context with the outbound decision information attached:
```go
type Route interface {
// A Route is also a routing context.
Context
// GetOutboundGroupTags returns the detoured outbound group tags in sequence before a final outbound is chosen.
GetOutboundGroupTags() []string
// GetOutboundTag returns the tag of the outbound the connection was dispatched to.
GetOutboundTag() string
}
```
Here, `OutboundGroup` is a concept managing a …
> Routing: Implement Route interface as Router's result

- app/stats/channel.go
- app/stats/channel_test.go
- app/stats/counter.go
- app/stats/counter_test.go
- app/stats/stats.go
- app/stats/stats_test.go
- features/stats/stats.go
Stats Channel feature is originally designed to run forever when registered. However, since #171 and #172 introduces unregistering logic for Stats Manager to release resources, it is no longer appropriate for Channel to keep resources like goroutine when unregistered, which poses potential memory leak threat.
This PR implements `common.Runnable` interface for Stats Channel feature, to enable Channel to releases resources like goroutine when no longer needed, and to be restarted at any time when subscribed again.
Aftering learning many concurrency details of goroutine and gochannels for several days, Stats Channel is now implemented in a heavy but more flexiable way, while performance is also increased by reducing the potential use of goroutines. 
Since Stats Channel is implemented with …
> Stats: Implement common.Runnable for Channel feature

- proxy/vless/encoding/addons.go
- proxy/vless/inbound/inbound.go
- proxy/vless/outbound/outbound.go
具体改变：每个 UDP 载荷前加两字节长度的 length，最大值为 2048-2=2046。若不使用 Mux，服务端与客户端均需升级至 v4.30.0+。这是 VLESS 公测版（0）协议结构本身唯一一次 breaking change，正式版（1）的服务端预计会长期同时支持该版本，第三方客户端的实现应当尽快跟进。
> VLESS UDP over TCP struct breaking change

- infra/conf/trojan.go
- infra/conf/vless.go
When fall back to abstract unix domain socket which is created by haproxy, the path needs to use the full length of RawSockaddrUnix.Path. So we need an option "padding" in FallbackObject to handle this situation.
> fix fall back to abstract unix domain socket in vless and trojan

- go.mod
- go.sum
[https://github.com/grpc/grpc-go/issues/3945#issuecomment-709487629](https://github.com/grpc/grpc-go/issues/3945#issuecomment-709487629)
由于grpc 1.33.0为不稳定版本，已被删除，建议回滚1.32.0，或等待2周后的1.33.1
> grpc: rollback from 1.33.0 to 1.32.0

- main/distro/all/all.go
In runtime, v2ray calls v2ctl ONLY to load json file. 
V2ray should work perfectly fine when json is loaded internally, that way v2ctl is NOT needed to run it.
V2ctl is still provided so no feature is missing. Binary size remains unchanged. 
There is no good reason not to do it.
> Load JSON internally by default

- proto.go
This PR: 修复在 Windows 环境中不使用正确的工具生成`grpc code`的问题。
在 Windows 中 filepath.Walk 得到的path是`proxy\vless\encodin\addons.proto`，而`ProtoFilesUsingProtocGenGoFast`的key是`proxy/vless/encoding/addons.proto`。
> fix: vprotogen in windows

- common/dice/dice.go
- common/dice/dice_test.go
Heavily inspired by math/rand. with ~20% performance improvement (BenchmarkInt31 vs. BenchmarkIntn).
\# go test -bench=. -benchmem -run=none
goos: darwin
goarch: amd64
pkg: v2ray.com/core/common/dice
BenchmarkRoll1-4    	1000000000	         0.329 ns/op	       0 B/op	       0 allocs/op
BenchmarkRoll20-4   	43471560	        24.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkIntn1-4    	52293325	        22.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkIntn20-4   	46995854	        24.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkInt31-4    	62762128	        18.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkIntn-4     	52576292	        22.6 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	v2ray.com/core/common/dice	9.313s
> Optimize rand.Intn(65536) to rand.Int63() >> 47,  before:22.6ns/op, after:18.6ns/op

- .github/workflows/release.yml
- release/friendly-filenames.json
reference #491 
added an additional build for android arm64 on github actions
working fine on my branch, see: [action](https://github.com/young-zy/v2ray-core-1/actions/runs/419022296)
> add build for android on github actions

- proxy/socks/client.go
- proxy/socks/protocol.go
- When you connect to a non-localhost socks5 server, in the response of a UdpAssociate from a socks5 server, the remote address may be `::` or `0.0.0.0`. The previous behavior is to connect to the remote address in the response, which obviously fails.
- This PR changes the behavior to dial to the outbound server's address when the remote address in the response is `::` or `0.0.0.0`.
- Rename `cmdUDPPort` to `cmdUDPAssociate` for clarity.
> 🧦 Fix socks client UDP outbound's wrong destination

- proxy/socks/protocol.go
- proxy/socks/server.go
- Previously, without specifying the server IP, the remote address in the response to a UdpAssoicate command is `127.0.0.1`, which might break UDP for non-localhost clients.
- This PR changes it so that, localhost clients get responses with the corresponding loopback IP, non-localhost clients get responses with the corresponding `net.AnyIP` or `net.AnyIPv6`.
- The new behavior is also consistent with many other implementations. So the compatibility is guaranteed. It also makes specifying server IP optional.
> 🎳 Refine socks5 server UdpAssociate response behavior

- common/log/access.go
- common/serial/string.go
This PR eliminates the trailing whitespace in logger outputs.
> 🕳 Prevent trailing whitespaces in logs

- infra/conf/trojan.go
- infra/conf/vless.go
- testing/scenarios/transport_test.go
- transport/internet/domainsocket/listener_test.go
- transport/internet/system_listener.go
- domain socket tests create UDS in `/tmp/*`, which is not supported by Android
- allow abstract UDS with padding on Android
> Refine Android build

- infra/conf/merge/merge.go
- main/commands/all/api/shared.go
- main/commands/all/api/shared_test.go
- main/commands/all/convert.go
The PR fixes api commands output of responses(My bad):
https://github.com/XTLS/Xray-core/issues/8#issuecomment-738644701
https://github.com/XTLS/Xray-core/issues/32#issuecomment-738714524
@rprx It is better to ignore empty outputs like `{}`
```go
if isEmpty(m) {
// avoid outputs like `{}`, `{"key":{}}`
return
}
```
> fix commands issues

- app/dispatcher/default.go
- app/dns/nameserver_doh.go
- app/dns/nameserver_quic.go
- app/router/command/config.go
- app/router/router.go
- common/session/session.go
- features/routing/context.go
- features/routing/session/context.go
`SkipRoutePick` is set from DNS DOH module, previously it had the most high priority that skips out all the routing rules, to prevent 
prevents resolving dead loop. 
But actually only need to skip out the DNS client part inside the matcher.
> fix bug not matching routing rules

- proxy/trojan/server.go
去掉common.Must()判断，应该可以修复[https://github.com/v2fly/v2ray-core/issues/495](https://github.com/v2fly/v2ray-core/issues/495)
> Do not panic when UDP dispatcher fails to write response

- app/router/condition.go
- app/router/condition_test.go
- app/router/config.go
- common/strmatcher/ac_automaton_matcher.go
- common/strmatcher/benchmark_test.go
- common/strmatcher/matchers_test.go
- common/strmatcher/strmatcher.go
I implemented a faster domainmatcher based on **AC automaton**, which is about 30% faster than the current implementation in local testing. And it combines the matching of **sub domain**, **plain domain**, and **full domain** routing rule to make it easier to maintain.
The figure below is a comparison of the new and old implementation benchmarks.
> A faster DomainMatcher implementation

- app/dns/dns.go
- app/dns/dns_test.go
- app/dns/dnscommon.go
- app/dns/dnscommon_test.go
- app/dns/hosts.go
- app/dns/hosts_test.go
- app/dns/nameserver.go
- app/dns/nameserver_doh.go
- app/dns/nameserver_fakedns.go
- app/dns/nameserver_local.go
- app/dns/nameserver_local_test.go
- app/dns/nameserver_quic.go
- app/dns/nameserver_quic_test.go
- app/dns/nameserver_udp.go
- app/router/router_test.go
- features/dns/client.go
- features/dns/localdns/client.go
- features/routing/dns/context.go
- go.mod
- proxy/dns/dns.go
- proxy/freedom/freedom.go
- testing/mocks/dns.go
See discussion in #406.
Only internal is changed, there is no change in config. Fakedns still function as one of the normal item in dns object.
> Routing and freedom outbound ignore Fake DNS

- transport/internet/tcp/hub.go
https://github.com/XTLS/Xray-core/issues/242#issuecomment-778889586
> Fix ALPN being set to h2 by default when using TCP

- proxy/vmess/encoding/server.go
- proxy/vmess/inbound/inbound.go
VMessAEAD have been used for a while, and no major issue is discovered and passed necessary security review and adopted recommend change. We can begin to discuss the decommission of legacy VMess header.
This PR is intended to start a discussion on this issue, not a decision to do so unless a consensus is reached.
> Deprecate legacy VMess header with a planned decommission

- infra/conf/dns.go
- infra/conf/dns_bootstrap.go
- infra/conf/dns_bootstrap_android.go
#572 当时是想着可以从已有的内置 DNS 中选择一个 DNS 作为 Android 默认的 DNS，但是后来就直接定为了 `8.8.8.8:53` 导致不需要内置 DNS 的用户会出现需要配置文件中填写 `"dns":{}` 才可以让代码生效的情况(https://github.com/v2fly/v2ray-core/discussions/692)
让其为 init 函数可以提高该操作的优先级，以防止某些用到 `net.DefaultResolver` 的函数在此更改前就已初始化而导致问题复现(https://github.com/v2ray/v2ray-core/issues/1909)
此更改依然仅对 Android 生效，不会影响其他的平台
> Android 默认 DNS  不再需要配置文件

- app/dns/dns.go
- app/router/condition.go
- app/router/condition_test.go
- app/router/config.go
- common/strmatcher/mph_matcher.go
- common/strmatcher/strmatcher.go
As you can see, the mph domain matcher is 30% faster than the original domain matcher, which is comparable to the pure ac automata.
related issue: https://github.com/XTLS/Xray-core/issues/192
* convert domain names to lowercase when matching domain (`app/router/condition.go`)
* rename domain matcher config `hybrid` to `mph`
* add a minimal perfect hash domain matcher
* remove the hybrid domain matcher
**Note**: The place where `app/dns/dns.go` involves domain name matching has not been modified.
> Add minimal perfect hash domain matcher

- proxy/dns/dns.go
> Fix: remove AA header flag in DNS query

- context.go
- functions.go
as for v2fly/v2ray-core#698 
ctx initialization for core.Dial() requires this, as from core.RequireFeatures() introduced in dispatcher.newFakeDNSSniffer().
```golang
ctx = context.WithValue(ctx, vcore.V2rayKeyValue, p.v)
```
> feat: export (const.)core.v2rayKey

- transport/internet/quic/dialer.go
- transport/internet/quic/hub.go
当前QUIC传输协议每30秒无数据传输就会断开连接，影响许多推送服务的稳定性，并造成一定的资源消耗。
解决方法很简单，协商参数中加上`KeepAlive:true`即可。
> fix QUIC disconnecting issue

- app/dns/dns.go
- app/dns/hosts.go
- app/dns/hosts_test.go
- infra/conf/dns.go
- infra/conf/dns_test.go
Now you can set `hosts` in `dns` section like this:
```json
{
"dns": {
"hosts": {
"ad.example.com": "127.0.0.1",
"ads.example.com": ["127.0.0.1", "::1"],
"geosite:category-ads": "127.0.0.1",
"geosite:category-ads-all": ["127.0.0.1", "::1"]
}
}
}
```
If set IPs together with domains, only the first proxied domain `one.example.com` will be returned and all IPs will be ignored:
```json
{
"dns": {
"hosts": {
"ads.example.com": ["127.0.0.1", "::1", "one.example.com", "two.example.com"]
}
}
}
```
> Feat: DNS hosts support multiple addresses

- app/router/condition_geoip_test.go
- app/router/condition_test.go
- common/platform/others.go
- infra/conf/dns_test.go
- infra/conf/router_test.go
PR #869 introduces a bug that leads to failure to read geo files paths from `v2ray.location.asset` environment variable.
> Fix: v2ray.location.asset env not working

- app/dns/nameserver_fakedns.go
fix https://github.com/v2fly/v2ray-core/issues/919#issuecomment-822294415
return ErrEmptyResponse when fakedns get 0 result
> Fix: return ErrEmptyResponse for fakedns

- infra/conf/fakedns.go
- Add FakeDNS default config according to `queryStrategy` in `dns`
- Use `fc00::/18` as default FakeDNS IPv6 IP pool
- Refine JSON unmarshal of FakeDNS config
- Fix case-sensitive string matching
> Fix: FakeDNS IPv6 & refine JSON unmarshal

- app/router/condition_geoip_test.go
- app/router/condition_test.go
- common/geodata/cache.go
- common/geodata/decode.go
- common/geodata/decode_test.go
- common/geodata/errors.generated.go
- common/geodata/load.go
- infra/conf/geodata.go
- infra/conf/observatory.go
- infra/conf/router.go
This PR implements a simple decoder based on LEB128 used in protobuf. It reads geo files byte by byte to reduce peak memory usage when V2Ray parses configuration.
If the decoder fails to decode the geo file, it will fallback to the original ReadFile method to keep backward compatibility.
About protobuf encoding and decoding, read https://developers.google.com/protocol-buffers/docs/encoding
> Refactor: memory-efficient geo file decoder

- format.go
- infra/vformat/main.go
Use customized `goimports` utility to remove empty lines in go `import` blocks
> Infra: use customized goimports

- app/dns/fakedns/fake.go
Fix the following edge cases:
```
{
fakedns: {}
}
```
or
```
{
fakedns: []
}
```
> Fix: FakeDNS prints error with empty config

- app/observatory/observer.go
- infra/conf/observatory.go
Fix following edge case:
```json
{
"observatory": {}
}
```
> Fix: observatory starts with empty config & fails to close

- common/geodata/cache.go
- common/geodata/decode.go
This PR resolves the performance issue of the new geodata decoder and export methods and errors to 3rd parties.
> Refinement: geodata decoder remove unnecessary GC & export methods for 3rd party

- common/platform/others.go
- common/platform/platform_test.go
- common/platform/windows.go
Fix `GetAssetLocation` method for external geo files like the following:
```
ext-ip:/path/to/your/customized/geoip.dat:cn
ext:/path/to/your/customized/geoip.dat:custom-cidr
ext:/path/to/your/customized/geosite.dat:custom-list
```
> Fix: GetAssetLocation for external geo files

- .github/workflows/deb.yml
Just build debian package on push event after changing the following paths or files to save GitHub organization free space quota:
```
.github/workflows/deb.yml
release/debian/*
```
> Chore: just build deb package on some cases to save space quota

- infra/control/main/main.go
> Fix: v2ctl is unable to create geo data loaders

- common/protocol/tls/cert/cert.go
- transport/internet/tls/config.go
Fix #997 
P.S. 因为VMess协议允许Server/Client的时间误差为90s，因此为了保证在该时间误差下生成的证书依旧可用，我将生成证书的提前时间从1分钟增加为2分钟。同时将证书的有效期也延长为1小时2分钟，这样在大量连接的情况下，证书生成间隔为约整1小时，便于从日志中找出相关问题。
> Fix: new cert issuing is incorrectly delayed

- app/dns/nameserver_tcp.go
This PR should fix the problem that routing rule is not applied for DNS Server in TCP:// schema. Related Issue: #1143 
```
dest := net.TCPDestination(net.DomainAddress(url.Hostname()), port)
```
The `AddressFamily` for the  `Address` in `dest` here is actually a Domain. During Router's `PickRoute` process, it will match against the **domain** list of the router rule, not the IP list, so the routing rule with IP addresses will never be applied.
use `net.ParseAddress` instead, it will return the right type automatically.(Although the address here is supposed to be IP address).
> fix: routing rule not applied for DNS Server in TCP:// schema

- app/dns/nameserver_quic.go
This Pull Request is inspired by #1144.
I think routing may cannot route DNS over QUIC with IP Address.
Because AdGuard DNS is the only Public DNS that supported DNS over QUIC, and it not supported SNI with IP Address, so I didn't test it.
> Fix: routing cannot route DNS over QUIC with IP

- app/router/condition_geoip.go
The length of IPv4 address in Go standard library could be 16
if it is in IPv6-mapped-IPv4 format.
> Fix: IP length not deterministic

- proxy/shadowsocks/client.go
I am not sure if it makes sense
> Send shadowsocks handshake with payload if available

- app/dns/nameserver_doh.go
- common/buf/multi_buffer_test.go
- common/common.go
- common/drain/drainer.go
- common/log/logger_test.go
- infra/conf/geodata/memconservative/cache.go
- infra/control/certchainhash.go
- infra/control/config.go
- infra/vprotogen/main.go
- main/confloader/external/external.go
- main/main.go
- testing/scenarios/common.go
- testing/scenarios/feature_test.go
- testing/scenarios/http_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
> refactor: move from io/ioutil to io and os package

- common/strmatcher/matchergroup_mph.go
- common/strmatcher/matchergroup_mph_test.go
As per description in https://github.com/v2fly/v2ray-core/discussions/1275#discussioncomment-1559883:
> `MphMatcherGroup` uses an algorithm [Hash, displace, and compress](http://cmph.sourceforge.net/papers/esa09.pdf) to construct a minimal perfect hash table. It involves `1. a normal hash function`, and `2. a series of hash functions independent to each others`.
> 
> This is how this `MphMatcherGroup` works:
> 
> #### First level hash: RollingHash
> Rolling hash is chosen here because we can easily calculate the hash of a full domain and all its subdomains.
> 
> We obtain a seed from the result of first level hash.
> 
> #### Second level hash: MemHash
> One of second level functions is selected according to the seed obtained from first level hash.
> 
> This is done by choosing golang …
> Refactor strmatcher.MphMatcherGroup

- main/commands/test.go
`test` should have the same config loading behavior as `run` as declared here
https://github.com/v2fly/v2ray-core/blob/ed9641dad1ab971e2977e26f2fd4545eb6524e45/main/commands/test.go#L19_L25
> Fix test command does not load default config.json

- transport/internet/headers/http/http.go
- transport/internet/headers/http/linkedreadRequest.go
Private function `readRequest`  has changed since 1.17. 
```diff
-func readRequest(b *bufio.Reader, deleteHostHeader bool) (req *Request, err error) {
+func readRequest(b *bufio.Reader) (req *Request, err error) {
```
Golang related commit : https://github.com/golang/go/commit/acb189ea59d7f47e5db075e502dcce5eac6571dc#diff-58d1202218e4b5db623ceb4abddb3c166adc4c34a327c1c9df106191edc370d2R1022
fixed: #1265
> fix: readRequest API changed since go1.17

- transport/internet/quic/conn.go
- transport/internet/quic/dialer.go
- transport/internet/quic/hub.go
implement `SetReadBuffer` and `SetWriteBuffer` to fix #1024
> Feat: implement set buffer methods in QUIC sysConn

- testing/scenarios/tls_test.go
This issue is tricky but I think it is the right fix:
- The log show no other error but a simple timeout
- The timeout happen at the first attempt
- Configuration has tls.Certificate{)
- The other tests in the same file file has 20 or 40 seconds timeout, while these tests only have 2 seconds
Examples of error logs:
> === RUN   TestTLSOverKCP
> 2021/10/16 01:24:44 [Info] All server closed.
> Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.2 darwin/amd64)
> A unified platform for anti-censorship.
> Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.2 darwin/amd64)
> A unified platform for anti-censorship.
> 2021/10/16 01:24:44 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:60064
> 2021/10/16 01:24:44 [Debug] app/proxyman/inbound: creating stream worker on …
> Increase some tls test timeout

- app/dispatcher/default.go
1. At the default log level(warning), if the default outbound is matched, there is no way to know whether a routing rule is matched or if the default route is taken.
2. Setting it to waring also reminds the user that a routing rule should be set for the special destination.
3. Knowing matched routing result clearly makes it easier to optimize the v2ray configuration.
4. If the log level in the configuration is simply set to info, there will be a lot of extra confusing info logs.
> Raising no route matched log level to Warning

- app/proxyman/outbound/outbound.go
example config:
```
{
"outbounds": [
{
"protocol": "vmess",
"tag": "tagA"
},
{
"protocol": "vmess",
"tag": "tagA"
}
]
}
```
first tagA outbound will be default outbound, the second outbound will replace first one in `taggedHandler `.
it looks weird.  like a orphan outbound.
> replace same tag default outbound handler

- common/platform/others.go
- common/platform/windows.go
- go.mod
- go.sum
ref: https://github.com/v2rayA/v2rayA/pull/393
search paths before the change:
- `/usr/local/share/v2ray`
- `/usr/share/v2ray`
- `/opt/share/v2ray`
- `$V2RAY_LOCATION_ASSET or executable dir`
search paths after the change:
- `$XDG_DATA_HOME/v2ray` or `~/.local/share/v2ray`
- `for dir in $XDG_DATA_DIRS; $dir/v2ray` or `/usr/local/share/v2ray` and `/usr/share/v2ray`
- `$V2RAY_LOCATION_ASSET or executable dir`
the only breaking change is that `/opt/share/v2ray` is no longer searched
> search for assets in xdg data directories on non-windows platforms

- app/dns/fakedns/fake.go
- app/dns/fakedns/fakedns_test.go
In rare cases different domains asking for dns will return the same IP, Add a mutex.
> Fix a concurrency issue in fakedns

- app/dns/nameserver_doh.go
I might have found out why issue #1556 happened. I have tested this issue and found it would only recurrent when a domain name has only A record. But it works well if has both A and AAAA.
https://github.com/v2fly/v2ray-core/blob/0bf1f2bae6d305a612d159b7ec9211c7db46632d/app/dns/nameserver_doh.go#L300-L329
`if` statements at line 300 and 308 do check `record.AAAA != nil && record.AAAA.RCode == dnsmessage.RCodeSuccess` they shouldn't, which should be done by method `getIPs()`. This causes error `errRecordNotFound` should returned by `getIPs()` can't be captured to `lastErr`, and finally the function returns at line 325 with error `ErrEmptyResponse`. This will let its caller `QueryIP()` returns directly, and skip "domain name re-querying" step we really need.
I did delete job at line 300 and …
> Fix failure of cache expired DNS record querying over DOH (v2fly#1556)

- transport/internet/tcp/hub.go
Allow zero port for listening port, namely random port.
> fix: net.Address type checking

- proxy/http/client.go
- proxy/proxy.go
- proxy/shadowsocks/client.go
- proxy/trojan/client.go
- proxy/vless/outbound/outbound.go
- proxy/vmess/outbound/outbound.go
PR #99 reduces an extra RTT when setting up the CONNECT tunnel
via http proxy, however, server-first protocols (such as MySQL)
will be unusable as v2ray keeps to wait for the client request.
This commit solves the problem by limiting the maximum waiting
time to 50 ms.
> proxy/http: Avoid getting stuck when using server-first protocols

- common/strmatcher/matchergroup_ac_automation.go
- common/strmatcher/matchergroup_ac_automation_test.go
As per description in https://github.com/v2fly/v2ray-core/discussions/1275#discussioncomment-1559881:
> Current v2ray provides an implementation of AC Automation, firstly used for Full, Domain and Substr matching, but soonly reduced to only Substr matching for memory consumption reason.
> 
> There are some problems with current implementation:
> 
> #### Algorithm not implemented correctly
> In AC Automation's algorithm, when entering a new node, its path through the fail pointer must be traversed until back to root node, or else it will fail to produce correct answers like this test case:
> 
> ```
> patterns: "apis", "googleapis.com"
> input: "gapis.com"
> ```
> 
> It has the substr "apis", but since it matches on "apis.com" out of "[google] apis.com" (the match is done on the input …
> Refactor strmatcher.ACAutomationMatcherGroup

- proxy/vmess/validator.go
- proxy/vmess/validator_test.go
https://github.com/XTLS/Xray-core/runs/4017048502?check_suite_focus=true
TestUserValidator randomly fail because the time.Now() in test is slightly later than the base time in validator. If it happened to land on another second, the verification on the edge of 120 seconds will fail.
Fix it by referencing the base time in validator.
> Fix TestUserValidator

- infra/conf/v5cfg/inbound.go
Fixes tproxy not working with jsonv5 config
> Fix: correct a type assertion of dokodemo simplified config

- app/router/config.go
- app/router/router.go
This fix routing condition not build for geoDomain in router rule with jsonv5 config.
---
Another simpler fix would be 
```diff
--- a/app/router/router.go
+++ b/app/router/router.go
@@ -239,7 +239,7 @@ func init() {
}
rule.SourcePortList = portList.Build()
}
-                       rule.Domain = v.Domain
+                       rule.Domain = append(rule.Domain, v.Domain...)
if v.Networks != "" {
rule.Networks = net.ParseNetworks(v.Networks)
}
```
which makes routing condition a union of both "geoDomain" and "domain", which might not be desired. Hence this fix.
> Fix: build routing condition for geo domain

- transport/internet/sockopt_darwin.go
I have no darwin devices to test these changes, but the original code doesn't seem to be correct.
/cc @ValdikSS
> Fix: correct TCP keepalive sockopt names for darwin

- common/protocol/headers.go
Dear V2Fly Maintainers,
This patch will change the logic of cipher selection for security type "auto", which based on codes migrated from go standard library `crypto/tls`.  
In the previous, this took mistakes on devices which does not support AES-GCM hardware acceleration but have installed a 64-bit system, such as J1900 mini-PC with x86_64 system and Raspberry with aarch64 kernel. It influenced me and my friends so we used to specify `chacha20-poly1305` manually. And this might solve the problem.  
I will keep following on this, thank you!  
Best regards,  
Hellojack  
Refer: 
https://cs.opensource.google/go/go/+/master:src/crypto/tls/cipher_suites.go;drc=9e6cd3985dbcdcfe0ed2075be6dbe8c5d6de59cb;l=364
> Feat: refine the logic of security type AUTO

- app/router/router.go
- infra/conf/json/reader.go
- infra/conf/json/reader_test.go
- proxy/dokodemo/dokodemo.go
- proxy/shadowsocks/simplified/config.go
Fix: guard against nil pointer dereference of (*NetworkList)
See https://github.com/v2fly/v2ray-core/commit/adb7871f82895c091c3d7f4c530cddf11aa5ebb9#r81688365
----
Fix: json.Reader: fill output bytes as much as possible & don't hide errors
Improved JSON parsing state machine so `Read([]byte)` can accept byte array of any length. A testcase has been updated because of this change.
This fixes a infinite read with io.ReadFull()
To reproduce the bug, load an arbitrary json file containing more than 2048 non-comment bytes.
```bash
printf '{ "prop": "' > a.json
printf 'a%.0s' {1..2048} >> a.json
printf '" }\n' >> a.json
v2ray test -format jsonv5 -c a.json
```
V2ray would hangs forever at io.ReadFull().
> Fix config loading

- app/dispatcher/default.go
`fakedns+others` won't work due to this bug.
> Fix erroneous prefix checking

- .github/workflows/deb.yml
- release/debian/rules
It seems to be left over from https://github.com/v2fly/v2ray-core/pull/488
> Remove v2ctl from debian/rules

- app/router/condition_geoip.go
- go.mod
- go.sum
netaddr package was deprecated, see https://github.com/inetaf/netaddr#deprecated
> Refactor: replace netaddr package with netipx

- app/observatory/burst/config.pb.go
- app/observatory/burst/config.proto
- app/observatory/burst/healthping.go
Destination URL, need 204 for success, return default to chromium browser URL 
This is by default used by chromium based browsers and by all android >6 devices
> feat: Replace default Health Ping URL to HTTPS

- transport/internet/sockopt_darwin.go
- transport/internet/sockopt_windows.go
I don't have any device to test if it works on Mac OS.
> Windows IP_UNICAST_IF
> Gets or sets the outgoing interface for sending IPv4 traffic. This option does not change the default interface for receiving IPv4 traffic. This option is important for multihomed computers. The input value for setting this option is a 4-byte IPv4 address in network byte order. This DWORD parameter must be an interface index in network byte order. Any IP address in the 0.x.x.x block (first octet of 0) except IPv4 address 0.0.0.0 is treated as an interface index. An interface index is a 24-bit number, and the 0.0.0.0/8 IPv4 address block is not used (this range is reserved). The interface index can be used to specify the default interface for sending traffic for IPv4. The …
> Feat: add bind to device to Windows and Darwin

- app/router/strategy_leastload.go
the PR fixes `selectLeastLoad()` returns wrong number of nodes
> fix selectLeastLoad() returns wrong number of nodes

- infra/conf/merge/map.go
- infra/conf/mergers/merge.go
- infra/conf/mergers/merger_base.go
The PR fixes bugs of config mergers
> Fix: config merger fixes

- app/dispatcher/default.go
- common/strmatcher/matchers.go
- common/strmatcher/matchers_test.go
- proxy/dns/dns.go
There were two related bugs:
1. Domain `Mijia Cloud` overrides the destination, but cannot be resolved by any DNS server, thus failed to dial. See https://github.com/v2ray/v2ray-core/issues/2615.
2. Doing `nslookup { <v2ray-dns>` caused v2ray dns app using mph domain matcher to crash. Fixed by https://github.com/v2fly/v2ray-core/pull/1988.
They are all related to usage of an invalid domain. https://github.com/v2fly/v2ray-core/pull/806 tried to prevent the invalid domain from overriding the destination, but closed due to definition of `invalid` is not correct. But preventing invalid domain from being used (as destination, or by DNS app) is meaningful, so this PR uses a more formal validation method `ToDomain` from `common/strmatcher` module to resolve this issue.
`ToDomain` will convert a …
> [app/dispatcher] [proxy/dns] Support domain string validation

- app/dns/dns_test.go
- common/strmatcher/matchers.go
https://github.com/v2fly/v2ray-core/issues/2022 requests IDN support for DNS, and https://github.com/v2fly/v2ray-core/pull/2053 resolves it. 
In fact, the merged PR https://github.com/v2fly/v2ray-core/pull/2188 already resolves aforementioned issue. The tests from https://github.com/v2fly/v2ray-core/pull/2053 are good so added in this PR and thus closes #2022.
> [app/dns] Add tests for idn support

- app/proxyman/outbound/handler.go
- transport/internet/tcp/dialer.go
This is a merge request fixes a bug introduced in security engine, in which server name information is not supplied to security engine when TCP transport is used.
(Fix #2243)
> Fix servername not supplied to security engine (Fix #2243)

- .github/workflows/release.yml
- .github/workflows/stale.yml
According to GitHub, currently `set-output` command used in the workflow [is deprecated and will be disabled soon](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), which generates a lot of warnings.
This PR tries to update it.
> Fix deprecated 'set-output' in workflow

- .github/workflows/release.yml
- release/container/Containerfile
- release/container/downloadAssets.sh
This is pull request adds automatic container building for v2ray.
The container is build after a prerelease is generated.
It comes with two favor: 
- std: Just a binary.
- extra: std with geoip, site, and extra.
Important paths:
- /opt/v2ray/bin/v2ray : the v2ray binary
- /opt/v2ray/share/ : the data files (if exists)
- /opt/v2ray/etc/config.json : the config file (if exists)
It is BTW:
- reproducible: Anyone can generate the same container image, with the same input.
- cross build ready: The builder machine does not need to execute anything.
- fully automated: No manual intervention needed to produce the build.
- distroless: image does not come with a distro, thus produce a small image.
> Add Intergrated Container Image Building

- .github/workflows/release.yml
- common/protocol/quic/qtls_go118.go
- go.mod
- release/container/Containerfile
- release/container/downloadAssets.sh
- transport/internet/http/hub.go
A common use case is to put v2ray behind an http server. The http server verifies the host name then reverse proxy the traffic to v2ray.
So v2ray don't need to verify host again, just leave `httpSettings.host` empty.
> Skip validating on empty http host config

- transport/internet/system_dialer.go
- transport/internet/system_listener.go
The Keep-Alive configs may be overridden with golang default settings when `tcpKeepAliveInterval` is set without `tcpKeepAliveIdle`.
Adopt: https://github.com/XTLS/Xray-core/pull/1328
> Fix sockopt.TcpKeepAliveInterval

- app/proxyman/config.pb.go
- app/proxyman/config.proto
- app/proxyman/outbound/handler.go
- common/buf/buffer.go
- common/session/session.go
- infra/conf/v4/v2ray.go
- proxy/freedom/freedom.go
- transport/internet/dialer.go
`DomainStrategy` is a setting in freedom outbound that may convert a domain address to ip address for dialing using v2ray's own DNS. This PR made this setting available to all outbounds, for following reasons:
* For certain cases it would be very useful if an outbound could use v2ray's DNS to resolve its proxy address to use. E.g., to choose between ipv4 or ipv6 address of a domain, if either address has route of better quality.
* Freedom outbound's `DomainStrategy`'s implementation is problematic if underlying transport relies on the domain. E.g. HTTP/2 transport will use the domain in its SNI, but freedom outbound replaces it before calling `Dial()`, which is too early.  
This PR adds a `Resolver` field to `session.Outbound`, when set it will resolve the domain right before calling the …
> [app/proxyman] DomainStrategy support for all outbounds

- common/buf/buffer.go
V2Ray has a powerful tool that's seldom used (only 2 references in whole project): `bytespool`.
`bytespool` has built in 4 pools of size `2048`, `8192`, `32768` and `131072`. The most frequently used `buf.Buffer` only use the first 2048 byte pool. The other three pools are actually very suitable for payload of variable length that may exceed default 2048 bytes.
`bytespool` uses `Alloc()` and `Free()` pair to manage the bytes buffers. This PR extends `buf.Buffer` to:
* introduce a new `bytespools` ownership, to make use of this two functions to provide a Buffer that can hold more size than 2048
* provide a new function `NewWithSize(size int32)`, to return a buffer with capacity having at least the given size (Under the hood it will choose one of the four pools to provide a bytes buffer).
> [common/buf] Add bytespools ownership for buf.Buffer

- proxy/trojan/client.go
This pull request fix a bug introduced in https://github.com/v2fly/v2ray-core/pull/2225 that result in a broken UDP implementation in Trojan protocol when Packet Addr is used.
> Fix incorrect UDP length in Torjan Packet Addr

- proxy/trojan/client.go
- proxy/trojan/protocol.go
fix #2250
In some protocol, such as SMTP , the client will watiing the command send from server after TCP handshaked, so Trojan header should be send even if payload is empty.
> fix: always send Trojan header

- common/protocol/address.go
- common/protocol/headers.go
- proxy/trojan/protocol.go
- proxy/trojan/protocol_test.go
#2440 #1795
Every UDP packet should have some headers.
> proxy/trojan: fix writing UDP packet

- release/container/Containerfile
Use command to add args.
Also, add a default command to make it backward compatible with v4.
> build: set v2ray binary as an entrypoint

- app/router/weight.go
As discussion in #2523, add mutex to protect field `cache` may solve the problem.
> fix(router): panic caused by concurrent map read and write (v2fly#2523)

- app/dns/nameserver_doh.go
- common/protocol/http/sniff.go
- proxy/http/server.go
protocol prefixes listed in document: `http`, `tls`, `bittorrent`
current possible protocols:
from sniffer: `http1`, `http2`(invalid value), `tls`, `quic`, `bittorrent`, `fakedns` 
from http inbound: `http/1.1` (matches `http`, incorrect if it has stream settings)
from internal dns: `dns` (TCP and UDP DNS), `https` (DoH, matches `http` instead of `tls`), `quic` (DoQ)
possible protocols after this change:
from sniffer: `http1`, `tls`, `quic`, `bittorrent`, `fakedns`
from internal dns: `dns` (TCP and UDP DNS), `tls` (DoH), `quic` (DoQ)
> fix protocol matching in routing

- .github/linters/.golangci.yml
- transport/internet/request/roundtripper/httprt/httprt.go
This merge request restore ci linter's status to passing by:
- remove unused attribute from http roundtripper
- reduce dependency restrictions to denylist
> Fix CI breakage in 5.7.0

- infra/conf/v5cfg/root.go
This PR improves error messages when parsing the json config file.
Previously, when something is wrong in the config (especially json syntax errors), it's difficult for the user to know which part causes it.
In this PR, more user-friendly error messages are added.
> fix: improve error messages when parsing config in jsonv5

- transport/internet/grpc/hub.go
- transport/internet/http/hub.go
- transport/internet/system_listener.go
- transport/internet/tcp/hub.go
- transport/internet/transportcommon/listener.go
- transport/internet/websocket/hub.go
Fixes: #2554.
This PR add support to set permission for UDS when set listen field like `"listen": "/dev/shm/v2fly.sock,0666"`. And move the "close lock file" logic to system listen creator. As the previous logic would _never_ close and remove the lock file (the parent context could not got the value set by child).
> fix(transport): support to set permission for UDS and correctly close lock file

- infra/vprotogen/main.go
Protobuf has changed their versioning scheme to a language-specific one. Basically the major part of versioning is now language-specific and no longer important. 
Current releases are referred to using the minor version e.g. v24.0. For example, the output of `protoc --version` gives  
`libprotoc 24.0-rc3` while config.pb.go generated by protoc-gen-go still uses something like `v4.24.0--rc3`.
See also
[https://protobuf.dev/news/2022-05-06/](https://protobuf.dev/news/2022-05-06/)
[https://github.com/protocolbuffers/protobuf/issues/11440](https://github.com/protocolbuffers/protobuf/issues/11440)
[https://github.com/protocolbuffers/protobuf/issues/11123](https://github.com/protocolbuffers/protobuf/issues/11123)
> Chore: support the new versioning scheme of Protobuf

- app/tun/packetparse/udp.go
Fixes UDP packets being dropped in non-local routing path(e.g. forwarding to LAN or container veth) due to 0-TTL.
> fix: set TTL for incoming UDP IP packets from TUN with PacketAddr dispatcher

- main/commands/base/execute.go
Related issue: <https://github.com/v2fly/v2ray-core/issues/2029>
Last PR (closed): <https://github.com/v2fly/v2ray-core/pull/2089>
> Fix: empty usage message with undefined flag (reopen)

- app/proxyman/outbound/handler.go
Fixes https://github.com/v2fly/v2ray-core/issues/2448#issuecomment-1567714796
For outbounds like SOCKS5, VMESS, `domainStrategy` will only take effect on proxy server's address (because `domainStrategy` only applies for dialing). 
This PR applies `domainStrategy` to outbound handler's `Dispatch` method, so all outbound targets will be affected by `domainStrategy`. Therefore `domainStrategy` for SOCKS5 and VMESS will behave like Freedom outbound.
* √ Remote proxy server's address is affected by `domainStrategy`. 
* x Actual target address is not affected by `domainStrategy`.
* √ Remote proxy server's address is affected by `domainStrategy`. 
* √ Actual target address will be affected by `domainStrategy`.
> Apply DomainStrategy to outbound target

- infra/conf/v5cfg/outbound.go
- infra/conf/v5cfg/skeleton.go
Added `domainStrategy` field for `outbound` in JSONv5 configuration file. This feature was introduced in #2334 and is only available in the JSONv4 configuration format.
This pull request:
- Repair and close #2448
- Restore the ability to use internal DNS resolution with "freedom" outbound. Related commit 40d75fa.
Credits:
- @Vigilans for the feature implementation
- @YVjXuB for report the problem
Usage:
```json
{
"outbounds": [
{
"protocol": "freedom",
"tag": "freedom",
"domainStrategy": "USE_IP"
// USE_IP, Use_IP, UseIP, USE_IPV4, Use_IPv4, UseIPv4, USE_IPV6, Use_IPv6, UseIPv6
}
]
}
```
I was not able to create single commit by using web editor, please consider using squash when merging this pull request.
> Add DomainStrategy to JSONv5 outbound

- common/crypto/auth.go
- common/crypto/chunk.go
- go.mod
- infra/conf/v5cfg/outbound.go
- proxy/shadowsocks2022/client.go
- proxy/shadowsocks2022/client_session.go
- proxy/shadowsocks2022/encoding.go
- proxy/shadowsocks2022/ss2022.go
- proxy/shadowsocks2022/udp_aes.go
1. Added UDP Replay Detection
2. Added UDP Processor State Cache
3. Added More Detailed Output for Time Difference Error
> Shadowsocks2022 Client Implementation Improvements

- transport/internet/httpupgrade/config.go
- transport/internet/httpupgrade/dialer.go
resolves: [#2740](https://github.com/v2fly/v2ray-core/issues/2740)
```golang
package main
import (
"fmt"
"net/http"
"os"
)
func main() {
f1()
f2()
}
func f1() {
fmt.Println("f1:")
s := "//s123/randomstring123"
req, _ := http.NewRequest("GET", s, nil)
req.Write(os.Stdout)
}
func f2() {
fmt.Println("f2:")
s := "/s123/randomstring123"
req, _ := http.NewRequest("GET", s, nil)
req.Write(os.Stdout)
}
```
```shell
go run .
f1:
GET /randomstring123 HTTP/1.1
Host: s123
User-Agent: Go-http-client/1.1
f2:
GET /s123/randomstring123 HTTP/1.1
Host: 
User-Agent: Go-http-client/1.1
```
> fix: unexpected path in httpugprade

- infra/conf/v4/trojan.go
- infra/conf/v4/v2ray.go
- infra/conf/v4/vless.go
- infra/conf/v5cfg/inbound.go
add Windows support for Unix Domain Socket
[Windows Insider Build 17063 and later](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) does support Unix Domain Socket, but the UDS check logic has blocked using UDS in windows.
config (`yaml` format):
```yaml
log:
loglevel: warning
inbounds:
- listen: "C:\\path\\to\\v2ray-core\\build_assets\\v2ray.sock"
tag: v2ray
protocol: http
sniffing:
enabled: true
destOverride: ["http", "tls"]
settings:
auth: noauth
allowTransparent: false
outbounds:
- tag: freedom
protocol: freedom
routing:
domainStrategy: AsIs
rules:
- type: field
inboundTag: v2ray
outboundTag: freedom
```
```plain
V2Ray 5.13.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.2 windows/amd64)
A unified platform for anti-censorship.
Failed to start: …
```
> fix(conf): add Windows support for Unix Domain Socket

- .github/workflows/release.yml
- release/container/Containerfile
resolves #2477 
This implementation builds for all platforms in one workflow step. I think it makes sense since all binaries are already ready at that time.
Another option is to keep using strategy matrix but we will have to upload all image manifest archives to workflow artifacts and merge them in another workflow job as demonstrated [here](https://github.com/redhat-actions/buildah-build/issues/121#issuecomment-1683691170), which seems not worth the trouble in our case. But I am open for discussion.
Currently for each release, these tags will be added for different version ranges and variations. Take v5.11.0 for example:
* v5.11.0 (no suffix for std variation)
* v5.11
* v5.11.0-extra
* v5.11-extra
Besides, if it's not marked as a prerelease, these additional tags will be added:
* v5
* …
> Improve container image tags and timestamp

- common/platform/filesystem/file.go
- infra/conf/rule/rule_test.go
This is a security enhancement that avoid unsafe by default permission that allow read from other users.
> Allow setting permission on CopyFile helper

- app/router/strategy_random.go
- common/dice/dice.go
- infra/conf/v4/trojan.go
- infra/conf/v4/vless.go
- proxy/shadowsocks2022/encoding.go
- proxy/vmess/encoding/client.go
This pull request replaced unsafe math rand usage with crypto/rand for passively observable random choices.
> Fix unsafe math rand usage

- app/subscription/entries/nonnative/definitions/vmess.jsont
Add support to allow an alternative value for vmess:// link: tls = 0
(Fix https://github.com/v2fly/v2ray-core/issues/2907)
> Add support to allow tls=0 in vmess:// subscription

- .github/workflows/release.yml
follow up fix for #2757 😳
It seems the newly published images are single-arch. Went through a few manuals and it turned out that we should use `--manifest` instead of `--tag`.
Also `buildah` doesn't supports more than one `--manifest` arguments in one build, so we have to build each (`v5`, `v5.15`, `v5.15.0`, etc) separately even if they are identical images/manifests.
Ideally we can move `downloadAssets.sh`'s logic into Containerfile itself so we can build for multiple archs concurrently. However that would be a big change and I'd rather leave it as is for now.
> fix multiarch buildah command

- common/protocol/http/headers.go
This merge request add Keep-Alive header to removed hop by hop headers in http protocol proxy as per requested by https://www.rfc-editor.org/rfc/rfc9110.html.
> Add Keep-Alive to removed headers in RemoveHopByHopHeaders

- transport/internet/request/roundtripper/httprt/httprt.go
This merge request add timeout for http round tripper to avoid attack with slow request. Beaware in typical usage, the requests are already authenticated before it reachs V2Ray.
> Add timeout for http request roundtripper

- .github/workflows/release.yml
This pull request adds pie build mode support to v2ray binaries for binary hardening.
> Add pie build mode to all binary builds

- app/dns/nameserver_doh.go
- app/dns/nameserver_quic.go
According to [RFC 9250](https://datatracker.ietf.org/doc/html/rfc9250/#section-4.2.1-1), when sending queries over a QUIC connection, the DNS Message ID **MUST** be set to 0.
According to [RFC 8484](https://datatracker.ietf.org/doc/html/rfc8484#section-4.1), DoH clients using media formats that include the ID field from the DNS message header, such as "application/dns-message", SHOULD use a DNS ID of 0 in every DNS request.
Real-life case: `quic+local://223.5.5.5:853` requires a zero DNS Message ID.
Related pull request: #1325.
> Always use a DNS Message ID of 0 for DoH and DoQ

- infra/conf/merge/merge_test.go
- infra/conf/merge/rules.go
- infra/conf/merge/tag.go
Fixes https://github.com/v2fly/v2ray-core/issues/2981
> Fix DNS servers with same tag wrongly merged

- infra/conf/v4/v2ray.go
This allows tun to be configured in v4cfg:
```
"services": {
"tun": {
"name": "tun0",
"mtu": 1500,
"tag": "tun",
"ips": [{ "ip": [198, 18, 0, 0], "prefix": 15 }],
"routes": [
{ "ip": [0, 0, 0, 0], "prefix": 0 }
// , { "ip": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "prefix": 0 }
],
"enablePromiscuousMode": true,
"enableSpoofing": true
}
}
```
Fixes https://github.com/v2fly/v2ray-core/pull/2541#issuecomment-2076989572
> Support "services" root config in cfgv4

- infra/conf/v4/shadowsocks.go
- infra/conf/v4/socks.go
- infra/conf/v4/socks_test.go
- infra/conf/v4/trojan.go
packet_encoding setting for config v4
> feat: packet_encoding for config v4

- proxy/http/client.go
`iConn.(*tls.Conn)` will fail for a uTLS Conn. Use `security.ConnectionApplicationProtocol` to get ALPN instead.
> Fix HTTP2 proxy client with uTLS

- app/router/config.go
This fix fallbackTag not working when balancer type is set to "leastping"
Fixes #3100
> routing/balancer: fix fallbackTag missing on leastping balancer

- proxy/hysteria2/client.go
- proxy/hysteria2/config.go
- proxy/hysteria2/protocol.go
- proxy/hysteria2/server.go
- transport/internet/hysteria2/conn.go
- transport/internet/hysteria2/dialer.go
padding mechanism reference: https://github.com/apernet/hysteria/blob/master/core/internal/protocol/padding.go.
> Some fixes about Hysteria 2

- go.mod
Update Golang go.mod toolchain version to 1.22
> Update Golang go.mod toolchain version to 1.22

- transport/internet/grpc/dial.go
- transport/internet/hysteria2/dialer.go
When reviewing https://github.com/v2fly/v2ray-core/pull/3162#discussion_r1783655151, I found that hysteria2 and grpc dialer do not fill `ServerName` with server address if `ServerName` is not specified. All other dialers use `config.GetTLSConfig(tls.WithDestination(dest))` or `security.OptionWithDestination{Dest: dest})`.
> hysteria2, grpc: fix the use of GetTLSConfig

- common/protocol/tls/cert/cert.go
- testing/scenarios/tls_test.go
- transport/internet/tls/config.go
`ServerName` should be filled with server address if `tlsSettings.serverName` is not specified.
> ServerName is used to verify the hostname on the returned certificates unless InsecureSkipVerify is given. It is also included in the client's handshake to support virtual hosting unless it is an IP address.
It is rare to have a certificate with IP addresses as Subject Alternate Name. However, this is indeed a bug, and this can be tested with self-signed certificates. Maybe the original author confused `ServerName` with `SNI`.
> Fix tls.WithDestination ignoring IP address

- common/net/packetaddr/connection_adaptor.go
- common/net/packetaddr/packetaddr.go
- transport/internet/udp/dispatcher_packetaddr.go
Currently packetAddr does not works with domain address and will panic when encountered one.
This patch will drop packets with a domain address to prevent panic, while long term solution is being considered.
See also: https://github.com/v2fly/v2ray-core/issues/2783
> Drop unsupported domain address type in packet addr

- app/subscription/entries/nonnative/nonnative.go
This pull request fixes issue mentioned in https://github.com/v2fly/v2ray-core/issues/3206 that there is an infinite loop when vmess link are processed.
Root cause of error: an empty string is a valid base64 string, thus triggering an infinite processing loop.
> Fix infinite loop when parsing empty nonnative subscription content

- transport/internet/tls/utls/utls.go
`VerifyPeerCertificate` and `InsecureSkipVerify` are for verify remote server's certificate.
`ClientAuth` and `ClientCAs` are for client certificate auth, 
`SessionTicketsDisabled` will not be copied, because it will make fingerprints changed, and it seems that some browser not provide a simple way to disable session tickets, such as [Google Chrome](https://superuser.com/questions/461035/disable-google-chrome-session-restore-functionality).
> feat: copy some certificate related options for uTLS

- common/protocol/quic/sniff.go
May address https://github.com/v2fly/v2ray-core/issues/3316
In the issue report, witness two byte slices's addresses provided to`seal`:
```
github.com/v2fly/v2ray-core/v5/common/crypto.(*AEADAuthenticator).Seal(0xc00b3f0240, {0xc001567012, 0x0, 0x7ee}, {0xc001567000, 0x168, 0x800})
```
The dst's address is **0xc001567012**, the plain text's address is **0xc001567000**.
The dst's code is: https://github.com/v2fly/v2ray-core/blob/14bc04a889b65827aa6fffd310d329f6b47d0cf7/common/crypto/auth.go#L264-L269
The plain text's code is: https://github.com/v2fly/v2ray-core/blob/14bc04a889b65827aa6fffd310d329f6b47d0cf7/common/crypto/auth.go#L295-L304
Apparently, `eb` and `temp` are pointing to the same buffer. It means `buf.New()` returns a buffer twice.
So I found issue in QUIC sniffing in this PR: …
> Fix unreleased cache buffer in QUIC sniffing

- transport/internet/websocket/dialer.go
the `err` has been check abrove, so it is nil value,
check the errWrite != nil, should return `.Base(errWrite)`
> fix call newError Base with a nil value error `err`

- common/protocol/quic/sniff.go
- common/protocol/quic/sniff_test.go
From https://github.com/XTLS/Xray-core/issues/3914
概述：
一些奇怪的数据包 读出的 packet number length 有可能会大于 length 本身 导致切片读取错误(b[17:15]这样) 样例数据在原issue有 可自行验证 想了一下比较简单的粗暴的方法大概就是检验后直接返回错误
先发到这里的原因是Xray的是从fly这copy的(其实这个错误从最开始的旧QUIC嗅探嗅探器就存在的样子)
CC: @Vigilans
> QUIC sniffer: Fix potential slice panic

- transport/internet/kcp/connection.go
- transport/internet/kcp/output.go
This PR fixes two issues where buffers were not released.
1. `defer b.Release()` not woking because b is always null.
https://github.com/v2fly/v2ray-core/blob/77d2d1b1728decf4a6c3433b46992cb7f6cc8794/transport/internet/kcp/connection.go#L392-L393
2. SimpleSegmentWriter.buffer never release.
https://github.com/v2fly/v2ray-core/blob/77d2d1b1728decf4a6c3433b46992cb7f6cc8794/transport/internet/kcp/output.go#L24
> Fix buffer leak in mkcp transport protocol

- proxy/http/server.go
Fix #3362 
copied from https://github.com/XTLS/Xray-core/pull/4547 (
> HTTP inbound: Directly forward plain HTTP 1xx response header

- .github/linters/.golangci.yml
- .golangci.yml
- infra/conf/v5cfg/root.go
- transport/internet/tlsmirror/data.pb.go
- transport/internet/tlsmirror/data.proto
- transport/internet/tlsmirror/interface.go
- transport/internet/tlsmirror/mirrorbase/conn.go
- transport/internet/tlsmirror/mirrorcrypto/derive_key.go
- transport/internet/tlsmirror/mirrorenrollment/client.go
- transport/internet/tlsmirror/mirrorenrollment/config.pb.go
- transport/internet/tlsmirror/mirrorenrollment/config.proto
- transport/internet/tlsmirror/mirrorenrollment/enrollment.go
- transport/internet/tlsmirror/mirrorenrollment/errors.generated.go
- transport/internet/tlsmirror/mirrorenrollment/httpenrollmentconfirmation/client.go
- transport/internet/tlsmirror/mirrorenrollment/httpenrollmentconfirmation/clientbuilder.go
- transport/internet/tlsmirror/mirrorenrollment/httpenrollmentconfirmation/enrollment.go
- transport/internet/tlsmirror/mirrorenrollment/httpenrollmentconfirmation/errors.generated.go
- transport/internet/tlsmirror/mirrorenrollment/httpenrollmentconfirmation/hub.go
- transport/internet/tlsmirror/mirrorenrollment/httpenrollmentconfirmation/server.go
- transport/internet/tlsmirror/mirrorenrollment/keyderivation.go
- transport/internet/tlsmirror/mirrorenrollment/server.go
- transport/internet/tlsmirror/mirrorenrollment/serverenrollmentprocessor.go
- transport/internet/tlsmirror/server/client.go
- transport/internet/tlsmirror/server/client_conn.go
- transport/internet/tlsmirror/server/config.pb.go
- transport/internet/tlsmirror/server/config.proto
- transport/internet/tlsmirror/server/conn.go
- transport/internet/tlsmirror/server/hub.go
- transport/internet/tlsmirror/server/server.go
This pull request adds a Connection Enrollment verification system to TLSMirror. This system is designed to use a slower connection to verify if the connection to the tlsmirror inbound is being hijacked to the original site to detect if client is sending traffics that could not be processed by the original server. This feature close the hole that would allow an in path attacker to detect the connection.
> TLSMirror Connection Enrollment System

- .github/workflows/release.yml
The Github Action for generating release is not working because arm64 pie binary is not reproducible. This merge request workaround this issue by assigning prerelease binary a different name for arm64 pie.
> ci: annotate arm64 pie binary with prerelease mark
