v2fly/v2ray-core

app/dispatcher/default.go, common/log/access.go, proxy/http/server.go, proxy/shadowsocks/server.go, proxy/socks/server.go, proxy/vmess/inbound/inbound.go
https://github.com/v2ray/v2ray-core/pull/1725
=> access log add detour tag

infra/bazel/build.bzl
https://github.com/v2ray/discussion/issues/714#issuecomment-637034754
=> fix bazel not set home

infra/bazel/build.bzl
=> Revert "fix bazel not set home"

infra/bazel/matrix.bzl, main/targets.bzl, release/BUILD
https://github.com/v2ray/v2ray-core/issues/2595
似乎这样就可以了，请测试一下
=> Add windows arm build

proxy/dokodemo/dokodemo.go
=> Add access log for dokodemo inbound

azure-pipelines.yml
https://golang.org/doc/devel/release.html#go1.14.minor
=> Update Golang version to 1.14.6

proxy/vless/inbound/inbound.go
https://github.com/rprx/v2fly-github-io/blob/master/docs/config/protocols/vless.md
=> VLESS PREVIEW 1.3

release/install-release.sh
=> feat: Add obsolete warning for old script

common/stack/bytes.go
=> Fix a typo

app/policy/config.go, common/net/port.go, common/protocol/server_spec.go, proxy/dns/dns_test.go, proxy/freedom/freedom.go, proxy/http/client.go, proxy/shadowsocks/client.go, proxy/shadowsocks/server.go, proxy/socks/client.go, proxy/vless/outbound/outbound.go, proxy/vmess/outbound/outbound.go, transport/internet/http/hub.go
=> Fix according to go vet results

app/dns/server.go, common/strmatcher/strmatcher.go
=> Fix: Bound check when accessing DNS server's ipIndexMap

app/stats/stats.go, features/stats/stats.go
Error occurred in https://github.com/v2fly/geoip/actions/runs/245428313
=> Fix: app/stats.Manager does not implement features/stats.Manager

proxy/http/client.go
=> Fix the coarse-grained mutex in http outbound

infra/conf/vless.go, infra/conf/vless_test.go, proxy/vless/encoding/addons.go, proxy/vless/encoding/encoding.go, proxy/vless/inbound/inbound.go, proxy/vless/outbound/outbound.go, proxy/vless/vless.go
https://github.com/rprx/v2ray-vless/releases/tag/preview2
=> VLESS PREVIEW 2

infra/conf/vless.go, proxy/vless/encoding/encoding.go, proxy/vless/encoding/encoding_test.go, proxy/vless/inbound/inbound.go, proxy/vless/outbound/outbound.go
https://github.com/rprx/v2ray-vless/releases/tag/preview2.2
=> VLESS PREVIEW 2.2

proxy/trojan/server.go
应该可以修复问题，只是对于 UDP，可能每个载荷都会 log 一下。。。
=> Fix Trojan inbound access log

infra/conf/transport_internet.go, transport/internet/kcp/dialer.go, transport/internet/kcp/listener.go
https://github.com/v2fly/v2ray-core/issues/266
=> Add XTLS support to mKCP

app/dns/server.go, app/stats/channel_test.go, external/github.com/cheekybits/genny/generic/generic.go, external/github.com/cloudflare/sidh/internal/arith/generic.go, external/github.com/cloudflare/sidh/internal/isogeny/curve_ops.go, external/github.com/cloudflare/sidh/p503/arith_generic.go, external/github.com/cloudflare/sidh/p503/field_ops.go, external/github.com/cloudflare/sidh/p751/arith_generic.go, external/github.com/cloudflare/sidh/sidh/api.go, external/github.com/cloudflare/sidh/sidh/sidh.go, external/github.com/marten-seemann/qtls/13.go
https://goreportcard.com/report/github.com/v2fly/v2ray-core#misspell
=> Fix misspelling according to goreportcard result

transport/internet/kcp/listener.go
https://github.com/v2fly/v2ray-core/issues/300
=> Fix XTLS over mKCP

infra/conf/trojan.go, proxy/trojan/server.go, proxy/trojan/validator.go
=> Trojan Protocol Handler implements UserManager

transport/internet/kcp/sending.go
mkcp 在 SendingWorker 的 Flush 方法中，根据当前接收到的 ack 情况，以及延迟丢包情况（如果退避流控开启），计算实际发出的最大包数量 cwnd。但是似乎这里 cwnd 被赋值为最大包序号而非最大的包数量，导致实际允许发送的包的数量将随包序号递增，发送窗口往往会增加为数万个包。接收方会因为接收到的包超出接受窗口而大量丢弃超前发送的包。
但是这个 bug 实际上让 mkcp 拥有了暴力发包的特性，使得在恶劣的网络条件下能够以比较好的速度进行传输。遵照符合逻辑的发送窗口进行发包反而降低了吞吐，所以这里乘了个 20 以达到类似的暴力发包效果。
这个修改需要更多的讨论。
=> fix mkcp sending window

proxy/http/client.go
=> Disable 0-rtt mechanism for http/1 outbound

proxy/trojan/client.go, proxy/trojan/protocol.go, proxy/trojan/server.go
When using trojan, you can set the environment variable V2RAY_TROJAN_XTLS_SHOW=true to display the output of XTLS
=> add trojanXTLSShow.

transport/internet/kcp/cryptreal.go
=> change temporary variable to lower camel case

azure-pipelines.yml, release/bleedingrelease.sh, release/tagrelease.sh
due to https://github.com/v2fly/V2BuildAssist/pull/4
=> Update variables of release

testing/scenarios/common_coverage.go, testing/scenarios/common_regular.go
=> fix v5 test

common/errors/errors.go, common/errors/errors_test.go
=> format errlog output

infra/conf/router.go, infra/conf/router_test.go
=> Routing 支持键名 domains #476

infra/conf/dns.go, infra/conf/router.go
- Check edge cases(mostly empty strings) and return more specific errors
- Remove useless functions
=> dns & routing: refine rule parsing process

app/dns/dns.go
Fixes https://github.com/v2fly/v2ray-core/issues/529
=> Fix: DNS compatible with localhost nameserver

app/dispatcher/default.go, app/dispatcher/stats.go, common/log/access.go
=> Add traffic stat of every request in access log

app/dispatcher/default.go, app/dispatcher/stats.go, common/log/access.go
=> 🔙 Revert "Add traffic stat of every request in access log"

proxy/vmess/encoding/server.go, proxy/vmess/inbound/inbound.go
Expose a way to disable legacy VMess on server side.
=> support enforcing VMessAEAD via environment variable

common/platform/others.go
This should make v2ray installable via Homebrew on macOS ARM devices.
=> Add /opt to assets location

app/dns/dns.go, app/dns/nameserver.go
=> Fix panic: DNS rule index out of range

common/mux/client_test.go, infra/conf/gun.go, infra/conf/loopback.go, testing/mocks/dns.go, testing/mocks/log.go, testing/mocks/mux.go, testing/mocks/outbound.go, testing/mocks/proxy.go, transport/internet/dialer.go, transport/internet/grpc/dial.go, transport/internet/grpc/hub.go, transport/internet/tagged/tagged.go, transport/internet/tagged/taggedimpl/impl.go, v2ray_test.go
```
find . -type f -name "*.go" ! -name "*.pb.go" | xargs -I file sh -c 'goimports -w -local="github.com/v2fly/v2ray-core" file'
```
Run the above command in project root directory to format imports.
=> Chore: format import using goimports

app/dns/fakedns/fake.go, app/dns/fakedns/fakedns_test.go, infra/conf/fakedns.go
=> FakeDNS: use 198.18.0.0/15 as default IP pool

testing/scenarios/tls_test.go, transport/internet/http/dialer.go
=> Revert "Test: fix http2 dial timeout (#570)"

common/strmatcher/mph_matcher.go
=> fix matching when zero domain/full rules

.github/workflows/updateGeofile.yml
Reference: https://github.com/Loyalsoldier/geoip/pull/9
=> Chore: change Git user

.gitignore, infra/vprotogen/main.go
to block generation code from old protobuf version
=> Feat: vprotogen adds version detector

format.go, infra/vformat/main.go
Make codes comply with Golang style.
Just run `go generate format.go` before submitting a PR, then you are good to Go!
=> Feat: format code in one-key

functions.go
=> fix: ctx initialization for core.(functions)

proxy/vless/encoding/encoding_test.go
=> Chore: refine test

app/browserforwarder/forwarder.go, common/platform/securedload/embeddedhash.go, common/platform/securedload/file.go
=> Fix: secured loading path under windows

common/geodata/cache.go, common/geodata/decode.go
=> Fix: code not found in geo files

app/browserforwarder/forwarder.go, infra/conf/browser_forwarder.go
=> fix: call IP() when listenAddr is empty

infra/conf/transport_internet.go
JSON unmarshal is case insensitive in Golang
=> Fix: JSON tag case

app/dns/nameserver_doh.go, app/dns/nameserver_quic.go
=> Fix: DNS return value

.github/workflows/deb.yml, release/debian/changelog, release/debian/control, release/debian/rules
=> Fix: debian package

proxy/trojan/server.go
=> Fix: Trojan fallback cannot get ALPN

app/dns/dns.go
=> Fix queryStrategy ignored

app/reverse/bridge.go, app/reverse/portal.go, app/reverse/reverse.go
=> Fix: context of reverse

app/dispatcher/fakednssniffer.go
=> Fix Fakedns Instance Resolution Memory Leak by Avoid using Require

app/dns/dns.go
=> Fix: context of DNS simplified config

transport/internet/grpc/dial.go
=> make gRPC dialer accept socket config

proxy/vlite/outbound/outbound.go
=> Fix vliteu outbound status context

app/router/command/command_test.go
https://github.com/XTLS/Xray-core/pull/750
=> Fix flaky TestServiceSubscribeRoutingStats

app/dns/nameserver_quic.go
=> Feat: Change ALPN and default port of DNS over QUIC for rfc9250

config.go, infra/conf/jsonpb/jsonpb.go, infra/conf/v2jsonpb/v2jsonpb.go, infra/conf/v5cfg/init.go
=> Fix: load auto format config with io.Reader

app/dns/nameserver_quic.go
=> Fix: length of DNS over QUIC

transport/internet/udp/dispatcher_split.go
=> Feat: Increase idle timeout to 300s for udp split

infra/vprotogen/main.go
We are currently having issue with constant generated protobuf related change set in commits that make it significantly harder to understand the change set.
This PR solve this issue by removing the comment on the top of each generated protobuf file except for the one in the repo root.
=> chore: normalize generated .pb.go file to reduce unnecessary change

app/dns/dns.go
fix https://github.com/v2fly/v2ray-core/issues/2374
=> fix: fix dns missing DomainMatcher in init function

transport/internet/http/dialer.go
This regression is introduced in 21b7a00.
=> fix http2 chain proxy

common/crypto/auth.go, proxy/shadowsocks2022/method_aes128gcm.go, proxy/shadowsocks2022/method_aes256gcm.go
Fix a typo introduced in b6da3e8.
=> Fix ss2022 auth reader size overflow

transport/internet/transportcommon/listener.go
=> Fix `transportcommon.ListenWithSecuritySettings`

release/config/config.json, release/debian/changelog
更改配置文件时在 config.json 发现一个，顺便看到 debina 更改日志里也有一个。
=> style: remove random trailing spaces

.github/workflows/release.yml
This merge request update build Golang version to v1.23.
=> Update Go version to v1.23

app/subscription/entries/nonnative/definitions/shadowsocks.jsont, app/subscription/entries/nonnative/nonnative.go
This pull request add supports for parsing some `ss://` links.
=> Add support for parsing some shadowsocks links

transport/internet/tls/ech.go
https://github.com/v2fly/v2ray-core/pull/3162#discussion_r1783655151
It seems that the original author took no action to fix it, so I raised this PR.
=> Fix the use of ServerName in ECH config

.github/workflows/release.yml
The PIE build system was previously broken. This pull request adds PIE favor build for v2ray binary releases.
=> Fix broken pie build with generating seperate files

.github/workflows/linter.yml
This pull request update CI setting for linter by updating its action script version.
=> Update Linter CI setting

app/dispatcher/default.go, common/protocol/quic/sniff.go
This merge request restructure the QUIC sniffer to include fixed sniffing overall timeout and fixed buffer allocation.
=> QUIC Sniffer Restructure

app/router/condition_geoip_test.go
=> Fix: geoip test by pinning geoip.dat to specific version
